### ISSUE TITLE
/cvmfs/ara.opensciencegrid.org/trunk/ missing MacOS

### ISSUE THREAD

**Issue by anij31** [ara-software/cvmfs#10]
As mentioned in the installation instructions, it only has CentOS, but I'm using a `MacOS`. Is there a specific way to install this on MacOS or would you guys have to add another build process for it.

*Feel free to reach out to me at my email:* aniruddhajoshi31@gmail.com.

**Comment by bhokansonfasig** [comment]
I think the answer to this may depend a bit on how you're trying to access the software, but the short answer is that there are no plans right now for a MacOS build in the cvmfs space. There are a couple things I think you may be after here though, so let me expand a bit:

**Using the ARA software on a computing cluster which has access to cvmfs**
If what you're after is a working version of the ARA software on your university's computing cluster (e.g. `cobalt` at UW), then likely the CentOS directory is the one you will need. The operating system name of that directory should be matched to the operating system of the computing cluster (i.e. not the computer you're connecting *from*, but the computer you're connecting *to*). In most cases this is some version of EL7, and I think that the CentOS directory should work for any EL7 system. Since I'm unaware of any university computing clusters running MacOS, that's the reason I say we have no intentions of a MacOS build in the cvmfs space.

**Using the ARA software on a personal computer**
While this is somewhat less common, maybe you were hoping to run the ARA software on your personal computer. If that is the case then you can try running the build scripts from `/cvmfs/builders/trunk/` by following the `README`. They were written in the hopes of making such an installation easier, but be warned that it could still be a bit of a task getting everything in the right place and working properly.

Hopefully that clears things up a bit, but if you were trying to do something else let me know and we can try to get you up and running!

**Comment by anij31** [comment]
Thank you for getting back to me. I'm trying to get started with Data Analysis on the ARA Data. For that, I was suggested to get an account on my university's cluster that gives the access to the software stack. I own a MacBook, so my access to the cluster is through MacOS. I was hoping to do data analysis and run deep learning algorithms on the ARA root data on Jupyter or Google Collab. Even if I use Cent OS as an external bootable drive, it makes sense to utilize the power of Google Collab. I went through the ARA bootcamp pdfs and videos, but it was a bit fuzzy when trying to understand how to go about doing that.
________________________________

**Comment by clark2668** [comment]
Right, so if the cluster you are using is a unix/linux cluster, then the Centos distributions in cvmfs will likely work for you. Can we ask what you have in mind? If you are wanting to use google colab, you are probably trying to do some kind of machine learning work? Without knowing the specifics of your work, it's unlikely that you would need to access the raw data or simulation tools in colab. So you probably don't need to have ARA software in colab. For example, I suspect you could use cvmfs on your local computing cluster to reduce the raw data into npz or hdf5 files. And then you can put those files containing just features into colab. Let me know if I misunderstand you here.
